#!/bin/bash
if [ -z "$1" ]
  then
    git commit -m 'refactor: ' -e
  else
    if [ -z "$2" ]
      then
        git commit -m "refactor: $1"
      else
        git commit -m "refactor($1): $2"
    fi
fi
